### ISSUE TITLE
Poptávka: poznámka chybí v tabulce - bug

### ISSUE THREAD

**Issue by vojky** [bbscout/daruj-potrebne#1]
Nazdrar, 
v prvé řadě díky za tenhle projekt.

Přišel jsem na to, že formulář na kartě poptávka sice poznámku nabízí, ale v tabulce toto pole chybí.

**Comment by bbscout** [comment]
Nazdar,
díky za upozornění. Tenhle konkrétní bug jsem opravil vložením nového řádku `{ name: "Poznámka", key: "poznamka" },` do proměnné `REQUESTS_FIELDS ` . 

Konkrétně v souboru `Kód.gs` upravit tuto proměnnou:
```javascript
REQUESTS_FIELDS = [
  { name: "ID", key: "id" },
  { name: "Datum", key: "datum" },
  { name: "Věc", key: "vec" },
  //{ name: "Velikost", key: "velikost" },
  //{ name: "Kategorie", key: "kategorie" },
  { name: "Jméno", key: "jmeno" },
  { name: "Příjmení", key: "prijmeni" },
  { name: "Adresa / místo dodání", key: "adresa" },
  { name: "Telefon", key: "telefon" },
  { name: "Email", key: "email" },
  { name: "Poznámka", key: "poznamka" },
  { name: "Rezervace", key: "rezervace" },
  { name: "Nabízí", key: "nabizi" },
  { name: "Předáno", key: "predano" }
];
```
Pokud to máš už někde rozběhnuté, tak doporučuji přejmenovat list `Poptávky` na něco jiného a pak spustit v Apps Scriptu funkci `init()`. Ta vytvoří nový list již s poznámkou na správném místě. Případně vložit sloupec mezi sloupce `Email` a `Rezervace`.
