### ISSUE TITLE
Chyba při ukládání telefonu

### ISSUE THREAD

**Issue by bbscout** [bbscout/daruj-potrebne#2]
Telefon bez předvolby (+420) se do tabulky neuloží

**Comment by vojky** [comment]
@bbscout U sebe jsem to vyřešil pomocí : `if (item.telefon != "") {
    item.telefon = "'" + item.telefon;
    }`.
Pokud je do formuláře telefon zadaný, do tabulky se zapíše s ' na začátku.

**Comment by bbscout** [comment]
Chyba byla v použití chybného atributu `phone` místo `telefon`>
`item.telefon = !item.phone ? item.phone : "'" + item.telefon;` >> `item.telefon = !item.telefon ? item.telefon : "'" + item.telefon;`
